spring:
  application:
    name: wxshop-order
  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

wxshop:
  orderservice:
    version: 0.0.1

server:
  port: 8081

mybatis:
  config-location: classpath:db/mybatis/config.xml

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.github.order.service