CREATE TABLE USER
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR (100),
    TEL         VARCHAR (20) UNIQUE,
    AVATAR_URL  VARCHAR (1024),
    ADDRESS    VARCHAR(1024),
    CREATE_AT   TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT   TIMESTAMP NOT NULL DEFAULT NOW()
)
